version: '3.5'

services:

  db:
    build: ./db/
    container_name: dbpost
    restart: always
    volumes:
      - /microservice/db
    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpass
    networks:
      - appnet
    ports:
      - 5432:5432


  microservice:
    build: ./
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - POSTGRES_PASSWORD=postpass
networks:
  appnet:
    name: appnet
    driver: bridge
